version: '3.9'

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: ezu_site
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - VIRTUAL_HOST=www.ezupos.com,ezupos.com
    depends_on:
      - php
    networks:
      - services_multiple_site

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ezu_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - services_multiple_site
    external_links:
      - mysql:mysql
      - redis:redis

networks:
  services_multiple_site:
    external: true